### ISSUE TITLE
Create Token Authentication System

### ISSUE THREAD

**Issue by BluLupo** [Squirrel-Network/api_nebula#3]
oAUTH2 or JWT or alternative

**Comment by BluLupo** [comment]
https://pythonhosted.org/Flask-JWT/

**Comment by mdnmdn** [comment]
FLASK-JWT with its builtin features, in order to login, requires a payload as:

`{
   "username": "pippo",
   "password": "wowsecret",
}`

At this time we have only token, so in order to use:

`{
  "token": "supersecret"
}`

we need a different approach using creating JWT token manually, maybe with: https://pyjwt.readthedocs.io/en/latest/

@BluLupo is that ok?

**Comment by BluLupo** [comment]
Yes approved
